# Generated by Django 5.2.6 on 2025-10-20 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('software_name', models.CharField(blank=True, max_length=255)),
                ('software_version', models.CharField(blank=True, max_length=255)),
                ('discovered_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('HINT', 'Hint'), ('NORMAL', 'Normal'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=16)),
                ('module', models.CharField(blank=True, max_length=255)),
                ('current_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_DEVELOPMENT', 'In Development'), ('UNDER_REVIEW', 'Under Review'), ('IN_REGRESSION', 'In Regression'), ('IN_MODIFICATION', 'In Modification'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, default='OPEN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewed_tickets', to=settings.AUTH_USER_MODEL)),
                ('regressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regressed_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['current_status'], name='tickets_tic_current_5257fb_idx'), models.Index(fields=['assignee'], name='tickets_tic_assigne_8f75bf_idx'), models.Index(fields=['submitter'], name='tickets_tic_submitt_68f44d_idx')],
            },
        ),
    ]
