# Generated by Django 5.2.6 on 2025-11-14 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_qareview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(blank=True, max_length=255)),
                ('root_cause', models.TextField(blank=True)),
                ('self_test_report', models.TextField(blank=True)),
                ('self_test_screenshots', models.FileField(blank=True, null=True, upload_to='dev_reports/screenshots/')),
                ('regression_version', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, max_length=255)),
                ('github_pr_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dev_reports', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_reports', to='tickets.ticket')),
            ],
        ),
    ]
