# Generated by Django 5.2.6 on 2025-11-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_assigned_developer_devreport_assigend_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevReport',
        ),
    ]
