# Generated by Django 5.2.6 on 2025-11-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_devreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devreport',
            old_name='assigend_developer',
            new_name='assigned_developer',
        ),
    ]
